### ISSUE TITLE
GeoIP2-City-Europe - odd results

### ISSUE THREAD

**Issue by ottk3** [ChickenKyiv/amazon-ses-service#61]
Hi there,

we recently purchased the MaxMind **GeoIP2-City-Europe** database but getting pretty bad results for europe.
We are using the PHP-method (it says installed), but it can't determine my own ip address. Even the other found locations look some kind of odd.

> According to this provider, your current location is:
> Unknown Refresh
> Note: This GeoIP implementation has access to the following types of databases: City, Country.

While the [MaxMind Precision Demo](https://www.maxmind.com/en/geoip2-precision-demo) correctly determines my location in Germany.

The **GeoIP2-City-Europe.mmdb** was correctly extracted into the /misc directory using the automatic url download option with the following url:

`https://download.maxmind.com/app/geoip_download?edition_id=GeoIP2-City-Europe&suffix=tar.gz&license_key=<key>`

What are my options to check if all settings are correct?

Best regards,
Sven

**Comment by atherdon** [comment]
i'm not sure. i don't think we can help you :)
we building our own email server system for inner needs

>

**Comment by ottk3** [comment]
However I managed to open an issue here - sorry :D
